{{- if .Values.tls }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: secret-tls
data:
  tls.crt: {{.Files.Get "files/tls.pem" | b64enc}}
  tls.key: {{.Files.Get "files/tls.key" | b64enc}}
{{- end }}
